# 1. Specify the rust version
FROM rust:1.69.0 as build

# 2. create a new empty shell project
RUN USER=root cargo new --bin rust-docker
WORKDIR /rust-docker

# 3. Copy the files in your machine to the docker image
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

# 3. Build program in --release mode cache your dependencies
RUN cargo build --release
RUN rm src/*.rs

# 4. Copy source tree
COPY ./src ./src

# 5. build for release
RUN rm ./target/release/deps/rust_docker*
RUN cargo build --release

# 6. Final Base
FROM rust:1.69-slim-buster

# 7. copy the build artifact from the build stage 
COPY --from=build /rust-docker/target/release/rust-docker .

# 8. run the binary
CMD ["./rust-docker"]